name: Android CI

on: pull_request

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 17

    - name: Build android app
      run: ./gradlew :app:assembleDebug

    - name: Run Unit Tests
      run: ./gradlew :app:test
