name: macOS CI

on: pull_request

# Cancel any current or previous job from the same PR
concurrency:
  group: macos-${{ github.head_ref }}
  cancel-in-progress: true


jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build macOS shared code
        run: ./gradlew :g:common:compileKotlinMacOSArm64






